---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Remove default nginx file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Remove default nginx file
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create Nginx reverse proxy file
  file:
    path: /etc/nginx/sites-available/kibana-reverse-proxy
    state: touch

- name: Configure Nginx reverse proxy
  marker: ""
  insertafter: EOF
  blockinfile:
    path: /etc/nginx/sites-available/kibana-reverse-proxy
    marker: ""
    block: |
      server {
          listen 8083;
          server_name http://52.174.166.131;
         # auth_basic "Restricted Access";
         # auth_basic_user_file /etc/nginx/.kibana-user;
          location / {
              proxy_pass http://localhost:5601;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }

- name: Remove default nginx file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create symlink for Nginx configuration
  file:
    src: /etc/nginx/sites-available/kibana-reverse-proxy
    dest: /etc/nginx/sites-enabled/kibana-reverse-proxy
    state: link
    force: yes

- name: Enable and restart Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes

