- name: install node-exporter
  hosts: all
  become: yes
  roles:
  - node-exporter

- name: install monitoring tools
  hosts: monitorserver
  become: yes
  roles:
  - prometheus
  - grafana
  - nginx
