
- name: Update cache 
  apt:
    update_cache: yes 


- name: Install required packages
  apt:
    name: ['apt-transport-https' , 'apache2-utils']
    state: present


- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Enable Elasticsearch service
  systemd: 
    name: elasticsearch
    enabled: yes 
    state: started

- name: Configure Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^#node.name:', line: 'node.name: {{ node_name }}' }
    - { regexp: '^#cluster.name:', line: 'cluster.name: {{ cluster_name }}' }
    - { regexp: '^#network.host:', line: 'network.host: {{ elastic_network_host }}' }
    - { regexp: '^#http.port', line: 'http.port: {{ elastic_http_port }}' }

- name: Restart Elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted

