- name: Install Kibana 
  apt: 
    name: kibana
    state: present

- name: Enable Kibana service
  systemd: 
    name: kibana
    enabled: yes 
    state: started

- name: Configure Kibana
  lineinfile:
    path: "/etc/kibana/kibana.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#server.port:', line: 'server.port: {{ kibana_server_port }}'}
    - { regexp: '^#server.host:', line: 'server.host: {{ kibana_server_host }}'}
    - { regexp: '^#elasticsearch.hosts:', line: 'elasticsearch.hosts: ["http://localhost:9200"]'}

- name: Restart Kibana service
  systemd:
    name: kibana
    state: restarted

