---
- name: Install elastic search
  hosts: elk
  vars:
    cluster_name: 'my_cluster'
    node_name: 'my_node'
    elastic_network_host: localhost
    elastic_http_port: 9200
    kibana_server_port: 5601
    kibana_server_host: localhost
  become: yes
  roles:
    - elasticsearch
    - kibana
    - filebeat
    - logstash
    - nginx-reverse-proxy
