---
    - name: Install Logstash
      apt:
        name: logstash
        state: present
 
    - name: Start & enable Logstash service
      systemd:
        name: logstash
        enabled: yes
        state: started 

    - name: Create Logstash configuration file
      template:
        src: logstash.conf.j2
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644
    - name: Restart Logstash
      systemd:
        name: logstash
        state: restarted

